modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/FakeDomi/InvisibLights/issues"
[[mods]]
modId="invisiblights"
version="5.0"
displayName="InvisibLights"
displayURL="https://www.curseforge.com/minecraft/mc-mods/invisiblights"
credits="Domi"
authors="Domi, Rongmario"