modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/FakeDomi/InvisibLights/issues"
[[mods]]
modId="invisiblights"
version="1.0"
displayName="InvisibLights"
displayURL="https://www.curseforge.com/minecraft/mc-mods/invisiblights"
credits="Domi1819"
authors="Domi1819, Rongmario"